# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python testing, linting, formatting

on:
  push:
    branches: [master, rc-0.2.0] # Remove this before merging to master.
  pull_request:
    branches: [master, rc-0.2.0] # Remove this before merging to master.

jobs:
  lint_and_format_check_with_ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: "pyproject.toml"
          args: "format --check"
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: "pyproject.toml"
          args: "check"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -e ".[testing]"
        # run: |
        # pytest --cov cechmate
      # - name: Test with pytest
      # - name: Upload coverage results
      # uses: codecov/codecov-action@v5
      # with:
      # name: cechmate
      # verbose: true
      # fail_ci_if_error: true
